name: flutter_epub_reader
description: A simple EPUB reader app with local and HTTP sync support
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  path_provider: ^2.1.3
  epubx: ^4.0.0
  file_picker: ^10.3.3
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
